name = "blackroad-email-router"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "848cf0b18d51e0170e0d1537aec3505a"

[vars]
DOMAIN = "blackroad.io"
ORG_NAME = "BlackRoad OS"

[[kv_namespaces]]
binding = "AGENT_INBOXES"
id = "d3cbe4e1ab814905b8c29cad110001d1"
